version: "3"

# Create flask application service and nginx reverse proxy service

services:
  flask:
    build: .
#Modify .env file to define new string to print out
    env_file:
      - .env
    ports:
      - 5000:5000
    networks:
      - frontend

  nginx:
    image: nginx
    ports:
      - 80:80
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    networks:
      - frontend

networks:
  frontend:

  
